# Generated by Django 4.2.6 on 2023-10-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskdo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=10)),
                ("last_name", models.CharField(max_length=10)),
            ],
        ),
    ]
