# Generated by Django 4.2.6 on 2023-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskdo", "0002_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
